# Generated by Django 5.1.4 on 2024-12-13 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ds_project', '0002_course_course_name_course_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_id',
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
