# Generated by Django 5.1.4 on 2024-12-14 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ds_project', '0003_alter_course_course_id'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='score',
            name='score_primary_key',
        ),
        migrations.AddConstraint(
            model_name='score',
            constraint=models.UniqueConstraint(fields=('mssv', 'course_id', 'year_id', 'term_id'), name='score_primary_key'),
        ),
    ]
